### ISSUE TITLE
When you support full mod tables with ID dumping ...

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [MrComputerGhost/Testerino#1]
I f***ing love this concept please let me know when you need a tester!!!

**Comment by MrComputerGhost** [comment]
Considering the state of the mod and how early it is, most everything needs a lot of testing. If you want to help beta test before I throw up releases on Curse that would greatly be appreciated. Which concept specifically do you love?

**Comment by P3rf3ctXZer0** [comment]
Mod Support Schematics. Nothing sucks more than loosing all that hardwork on a structure and using carpenters blocks just to have to loose it when the world fails.
