### ISSUE TITLE
Unknown issue when using export

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [MrComputerGhost/Testerino#4]
TEST ENVIRONMENT JAR - Testerino-0.04.jar

This is how I wrote the command
/export x797 y81 z950 x824 y100 z922 test

This was the console result
"An unknown error occurred when attempting to perform this command."

ALSO TRIED

This is how I wrote the command
/export 824 100 922 797 81 950 test

This was the console result
"The second set of coordinates must be greater than or equal to the original set!"

**Comment by MrComputerGhost** [comment]
"The second set of coordinates must be greater than or equal to the original set!"

Exactly what it says.

You have: /export 824 100 922 797 81 950 test
You should have: /export 797 81 922 824 100 950 test
